name: "dbt_healthcare"
version: "1.0.0"
config-version: 2

profile: "dbt_healthcare"

models:
  dbt_healthcare:
    +materialized: view 
    staging:
      +schema: staging      
      +materialized: view
    marts:
      +schema: marts          
      +materialized: table
